### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR adds two buttons to get your app on F-Droid and Google Play 👍 

You can now eventually add the [fdroid](https://github.com/topics/fdroid) and/or [f-droid](https://github.com/topics/f-droid) tags that will appear on the right side of the repo.

### CODE REVIEW

**Review by NyxTrail — APPROVED** [review]
Thank you for this PR.

**Review by NyxTrail — COMMENTED** [review]
How do I merge this again?

**Comment by Poussinou** [comment]
> How do I merge this again?

Sorry I deleted my fork in the meantime, I think that's why you couldn't merge this PR again.

**Comment by NyxTrail** [comment]
Didn't realise you had replied. 

I had committed your changes manually.

https://github.com/NyxTrail/aksharam/commit/f0a145f2f9d756bc4b4c77251fb122aed58e1525

**Pull request merged**
